'use client';

import { useState } from 'react';
import { Copy, Check, FileText, Download, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import type { StudySession, ReviewPlan } from '@/app/types';

interface MarkdownExportProps {
  session: StudySession;
  reviewPlan?: ReviewPlan;
}

export function MarkdownExport({ session, reviewPlan }: MarkdownExportProps) {
  const [copied, setCopied] = useState(false);

  const generateMarkdown = () => {
    const date = new Date(session.date).toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      weekday: 'long'
    });

    const dayLabels = ['明天', '后天', '4天后', '7天后', '15天后', '30天后'];

    let markdown = `# 📚 ${date} 学习记录

> **📌 今日主题**: ${session.topic}  
> **📖 所属科目**: ${session.subject}

---

## ⏱️ 专注统计

| 指标 | 数值 |
|:-----|:-----|
| 🍅 番茄钟 | ${session.pomodoros} 个 |
| ⏰ 学习时长 | ${Math.floor(session.duration / 60)}小时${session.duration % 60}分钟 |
| 📊 完成度 | ${session.cornellNote.cues && session.feynmanOutput ? '100% ✅' : '进行中...'}

---

## 📑 康奈尔笔记

### 📌 线索栏
${session.cornellNote.cues ? session.cornellNote.cues.split('\n').map(line => `- ${line}`).join('\n') : '*暂无关键词*'}

### 📝 笔记栏
${session.cornellNote.notes || '*暂无详细笔记*'}

### 📋 总结栏
> ${session.cornellNote.summary || '*暂无总结*'}

---

## 🎓 费曼输出

${session.feynmanOutput ? `> ${session.feynmanOutput.replace(/\n/g, '\n> ')}` : '*暂无费曼输出*'}

---

## 🔄 艾宾浩斯复习计划

${
  reviewPlan 
    ? reviewPlan.reviewDates.map((rd, idx) => {
        const status = rd.completed ? '✅' : '⬜';
        const dateStr = new Date(rd.date).toLocaleDateString('zh-CN', {
          month: 'short',
          day: 'numeric',
          weekday: 'short'
        });
        return `- ${status} **${dateStr}** — ${dayLabels[idx] || `第${idx+1}次`}`;
      }).join('\n')
    : '*复习计划生成中...*'
}

---

> 💡 *坚持复习是巩固知识的关键！*
>
> 📝 *Generated by [StudyHub](https://studyhub.app) - 智能学习助手*

`;

    return markdown;
  };

  const handleCopy = async () => {
    const markdown = generateMarkdown();
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div 
      className="bg-white rounded-3xl shadow-xl overflow-hidden border border-gray-100"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.2 }}
    >
      {/* 头部 */}
      <div className="relative overflow-hidden">
        <div className="bg-gradient-to-r from-amber-500 via-orange-500 to-red-500 px-6 py-5">
          <div className="absolute inset-0">
            <div className="absolute top-0 right-0 w-32 h-32 rounded-full bg-white/10 blur-xl" />
            <div className="absolute bottom-0 left-1/2 w-40 h-40 rounded-full bg-white/10 blur-xl" />
          </div>
          
          <div className="relative z-10 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <motion.div 
                className="w-12 h-12 rounded-2xl bg-white/20 backdrop-blur flex items-center justify-center"
                animate={{ rotate: [0, 5, -5, 0] }}
                transition={{ duration: 2, repeat: Infinity }}
              >
                <FileText className="w-6 h-6 text-white" />
              </motion.div>
              <div>
                <h3 className="text-white font-display font-bold text-xl">博客 Markdown</h3>
                <p className="text-white/80 text-sm">一键复制到你的博客</p>
              </div>
            </div>
            
            {/* 复制按钮 */}
            <motion.button
              onClick={handleCopy}
              className={`relative px-5 py-2.5 rounded-xl font-medium transition-all flex items-center gap-2 ${
                copied
                  ? 'bg-green-500 text-white'
                  : 'bg-white text-orange-600 hover:bg-orange-50'
              }`}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: copied ? 1 : 0 }}
                transition={{ type: 'spring', bounce: 0.5 }}
              >
                <Check className="w-5 h-5" />
              </motion.div>
              <span>{copied ? '已复制' : '一键复制'}</span>
            </motion.button>
          </div>
        </div>
        
        {/* 装饰波浪 */}
        <svg className="absolute bottom-0 left-0 right-0" viewBox="0 0 1200 30" preserveAspectRatio="none">
          <path d="M0,30 C300,0 600,0 900,30 C1050,15 1150,15 1200,30 L1200,30 L0,30 Z" fill="#fff" />
        </svg>
      </div>
      
      {/* 预览内容 */}
      <div className="p-5">
        <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl p-4 overflow-auto max-h-[350px]">
          <pre className="text-xs text-gray-600 whitespace-pre-wrap font-mono leading-relaxed">
            {generateMarkdown()}
          </pre>
        </div>
        
        {/* 提示 */}
        <div className="flex items-center gap-2 mt-4 text-sm text-gray-500">
          <Sparkles className="w-4 h-4 text-amber-500" />
          <span>复制后可以直接粘贴到任何支持 Markdown 的博客平台</span>
        </div>
      </div>
      
      {/* 底部装饰 */}
      <div className="h-1.5 bg-gradient-to-r from-amber-500 via-orange-500 to-red-500" />
    </motion.div>
  );
}
